# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a612b46a85deda4f1434c84e61e9137"
name = "voucher-app"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
